name: digit_classifier
description: An app designed to classify digits in a picture from 0-9.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  scoped_model: ^1.1.0
  intl: 0.16.1
  gallery_saver: ^2.0.0
  flutter_slidable: ^0.6.0
  sqflite: ^1.2.0
  image_picker: ^0.8.2
  camera:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  tflite:
  meta: ^1.1.1
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/MNIST-CNN.tflite